### ISSUE TITLE
java.lang.RuntimeException: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by grassick** [mWater/cordova-plugin-wezka-nativecamera#5]
> "STACK_TRACE": "java.lang.RuntimeException: getParameters failed (empty parameters)\n\tat android.hardware.Camera.native_getParameters(Native Method)\n\tat android.hardware.Camera.getParameters(Camera.java:1759)\n\tat com.tmantman.nativecamera.CameraActivity$1.onTouch(CameraActivity.java:156)\n\tat android.view.View.dispatchTouchEvent(View.java:8040)\n\tat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)\n\tat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2140)\n\tat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)\n\tat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2112)\n\tat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)\n\tat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2112)\n\tat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)\n\tat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2112)\n\tat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)\n\tat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2112)\n\tat com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2295)\n\tat com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1622)\n\tat android.app.Activity.dispatchTouchEvent(Activity.java:2565)\n\tat com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2243)\n\tat android.view.View.dispatchPointerEvent(View.java:8240)\n\tat android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4672)\n\tat android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4538)\n\tat android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4096)\n\tat android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4150)\n\tat android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4119)\n\tat android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4230)\n\tat android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4127)\n\tat android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4287)\n\tat android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4096)\n\tat android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4150)\n\tat android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4119)\n\tat android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4127)\n\tat android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4096)\n\tat android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6461)\n\tat android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6378)\n\tat
android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6349)\n\tat android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6314)\n\tat android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6541)\n\tat android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)\n\tat android.os.MessageQueue.nativePollOnce(Native Method)\n\tat android.os.MessageQueue.next(MessageQueue.java:138)\n\tat android.os.Looper.loop(Looper.java:131)\n\tat android.app.ActivityThread.main(ActivityThread.java:5602)\n\tat java.lang.reflect.Method.invokeNative(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:515)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)\n\tat dalvik.system.NativeStart.main(Native Method)\n",

**Comment by grassick** [comment]
@broncha  I'm still getting this one in the latest version:

```
java.lang.RuntimeException: getParameters failed (empty parameters)
	at android.hardware.Camera.native_getParameters(Native Method)
	at android.hardware.Camera.getParameters(Camera.java:1759)
	at com.tmantman.nativecamera.CameraActivity$1.onTouch(CameraActivity.java:156)
	at android.view.View.dispatchTouchEvent(View.java:8040)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2140)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2112)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2112)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2112)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2112)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2295)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1622)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2565)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2243)
	at android.view.View.dispatchPointerEvent(View.java:8240)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4672)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4538)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4096)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4150)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4119)
	at android

```

**Comment by broncha** [comment]
@grassick This is not a memory issue. Looking at the trace, this is happening when user taps on the focus button, but the camera has already crashed.

I am going to need more context for this issue. Any logcat dumps from one of the issues?

**Comment by broncha** [comment]
Adding logcat output for reference:

<details>

```
08-25 17:52:08.261 W/FileTransfer(24069): Error getting HTTP status code from connection.
08-25 17:52:08.261 E/FileTransfer(24069): {\"target\":\"https:\\/\\/api.mwater.co\\/v3\\/images\\/f3133319712f4868aa7da11c9f2e904e?client=3cda012c1c620bff5eefe5334cc266c0\",\"http_status\":0,\"code\":3,\"source\":\"file:\\/\\/\\/storage\\/emulated\\/0\\/Android\\/data\\/co.mwater.clientapp\\/images\\/pending\\/original\\/f3133319712f4868aa7da11c9f2e904e.jpg\",\"exception\":\"Unable to resolve host \\\"api.mwater.co\\\": No address associated with hostname\"}
08-25 17:52:08.261 E/FileTransfer(24069): Failed after uploading 0 of 347240 bytes.
08-25 17:52:14.347 I/chromium(24069): [INFO:CONSOLE(12233)] \"About to take picture\", source: file:///storage/emulated/0/Android/data/co.mwater.clientapp/updates/update//js/app.js?_=1471016679464 (12233)
08-25 17:52:14.397 W/PluginManager(24069): THREAD WARNING: exec() call to Camera.takePicture blocked the main thread for 23ms. Plugin should use CordovaInterface.getThreadPool().
08-25 17:52:14.467 I/SensorManagerA(24069): getReportingMode :: sensor.mType = 1
08-25 17:52:14.477 D/SensorManager(24069): registerListener :: 0, BMA254, 200000, 0,  
08-25 17:52:24.667 W/CameraBase(24069): Camera service died!
08-25 17:52:24.667 W/CameraBase(24069): mediaserver's remote binder Camera object died
08-25 17:52:24.687 E/InputEventReceiver(24069): Exception dispatching input event.
08-25 17:52:24.687 E/MessageQueue-JNI(24069): Exception in MessageQueue callback: handleReceiveCallback
08-25 17:52:24.717 E/MessageQueue-JNI(24069): java.lang.RuntimeException: getParameters failed (empty parameters)

```

</details>
